Country.where(name: "China").first_or_create!.update!(population: 1_433_783_686)
Country.where(name: "India").first_or_create!.update!(population: 1_366_417_754)
Country.where(name: "United States").first_or_create!.update!(population: 329_064_917)
Country.where(name: "Indonesia").first_or_create!.update!(population: 270_625_568)
Country.where(name: "Pakistan").first_or_create!.update!(population: 216_565_318)
Country.where(name: "Brazil").first_or_create!.update!(population: 211_049_527)
Country.where(name: "Nigeria").first_or_create!.update!(population: 200_963_599)
Country.where(name: "Bangladesh").first_or_create!.update!(population: 163_046_161)
Country.where(name: "Russia").first_or_create!.update!(population: 145_872_256)
Country.where(name: "Mexico").first_or_create!.update!(population: 127_575_529)
Country.where(name: "Japan").first_or_create!.update!(population: 126_860_301)
Country.where(name: "Ethiopia").first_or_create!.update!(population: 112_078_730)
Country.where(name: "Philippines").first_or_create!.update!(population: 108_116_615)
Country.where(name: "Egypt").first_or_create!.update!(population: 100_388_073)
Country.where(name: "Vietnam").first_or_create!.update!(population: 96_462_106)
Country.where(name: "DR Congo").first_or_create!.update!(population: 86_790_567)
Country.where(name: "Germany").first_or_create!.update!(population: 83_517_045)
Country.where(name: "Turkey").first_or_create!.update!(population: 83_429_615)
Country.where(name: "Iran").first_or_create!.update!(population: 82_913_906)
Country.where(name: "Thailand").first_or_create!.update!(population: 69_037_513)
Country.where(name: "United Kingdom").first_or_create!.update!(population: 67_530_172)
Country.where(name: "France").first_or_create!.update!(population: 65_129_728)
Country.where(name: "Italy").first_or_create!.update!(population: 60_550_075)
Country.where(name: "South").first_or_create!.update!(population: 58_558_270)
Country.where(name: "Tanzania").first_or_create!.update!(population: 58_005_463)
Country.where(name: "Myanmar").first_or_create!.update!(population: 54_045_420)
Country.where(name: "Kenya").first_or_create!.update!(population: 52_573_973)
Country.where(name: "South Korea").first_or_create!.update!(population: 51_225_308)
Country.where(name: "Colombia").first_or_create!.update!(population: 50_339_443)
Country.where(name: "Spain").first_or_create!.update!(population: 46_736_776)
Country.where(name: "Argentina").first_or_create!.update!(population: 44_780_677)
Country.where(name: "Uganda").first_or_create!.update!(population: 44_269_594)
Country.where(name: "Ukraine").first_or_create!.update!(population: 43_993_638)
Country.where(name: "Algeria").first_or_create!.update!(population: 43_053_054)
Country.where(name: "Sudan").first_or_create!.update!(population: 42_813_238)
Country.where(name: "Iraq").first_or_create!.update!(population: 39_309_783)
Country.where(name: "Afghanistan").first_or_create!.update!(population: 38_041_754)
Country.where(name: "Poland").first_or_create!.update!(population: 37_887_768)
Country.where(name: "Canada").first_or_create!.update!(population: 37_411_047)
Country.where(name: "Morocco").first_or_create!.update!(population: 36_471_769)
Country.where(name: "Saudi Arabia").first_or_create!.update!(population: 34_268_528)
Country.where(name: "Uzbekistan").first_or_create!.update!(population: 32_981_716)
Country.where(name: "Peru").first_or_create!.update!(population: 32_510_453)
Country.where(name: "Malaysia").first_or_create!.update!(population: 31_949_777)
Country.where(name: "Angola").first_or_create!.update!(population: 31_825_295)
Country.where(name: "Mozambique").first_or_create!.update!(population: 30_366_036)
Country.where(name: "Yemen").first_or_create!.update!(population: 29_161_922)
Country.where(name: "Ghana").first_or_create!.update!(population: 28_833_629)
Country.where(name: "Nepal").first_or_create!.update!(population: 28_608_710)
Country.where(name: "Venezuela").first_or_create!.update!(population: 28_515_829)
Country.where(name: "Madagascar").first_or_create!.update!(population: 26_969_307)
Country.where(name: "North Korea").first_or_create!.update!(population: 25_666_161)
Country.where(name: "Ivory Coast").first_or_create!.update!(population: 25_716_544)
Country.where(name: "Cameroon").first_or_create!.update!(population: 25_876_380)
Country.where(name: "Australia").first_or_create!.update!(population: 25_203_198)
Country.where(name: "Taiwan").first_or_create!.update!(population: 23_773_876)
Country.where(name: "Niger").first_or_create!.update!(population: 23_310_715)
Country.where(name: "Sri Lanka").first_or_create!.update!(population: 21_323_733)
Country.where(name: "Burkina Faso").first_or_create!.update!(population: 20_321_378)
Country.where(name: "Mali").first_or_create!.update!(population: 19_658_031)
Country.where(name: "Romania").first_or_create!.update!(population: 19_364_557)
Country.where(name: "Malawi").first_or_create!.update!(population: 18_628_747)
Country.where(name: "Chile").first_or_create!.update!(population: 18_952_038)
Country.where(name: "Kazakhstan").first_or_create!.update!(population: 18_551_427)
Country.where(name: "Zambia").first_or_create!.update!(population: 17_861_030)
Country.where(name: "Guatemala").first_or_create!.update!(population: 17_581_472)
Country.where(name: "Ecuador").first_or_create!.update!(population: 17_373_662)
Country.where(name: "Netherlands").first_or_create!.update!(population: 17_097_130)
Country.where(name: "Syria").first_or_create!.update!(population: 17_070_135)
Country.where(name: "Cambodia").first_or_create!.update!(population: 16_486_542)
Country.where(name: "Senegal").first_or_create!.update!(population: 16_296_364)
Country.where(name: "Chad").first_or_create!.update!(population: 15_946_876)
Country.where(name: "Somalia").first_or_create!.update!(population: 15_442_905)
Country.where(name: "Zimbabwe").first_or_create!.update!(population: 14_645_468)
Country.where(name: "Guinea").first_or_create!.update!(population: 12_771_246)
Country.where(name: "Rwanda").first_or_create!.update!(population: 12_626_950)
Country.where(name: "Benin").first_or_create!.update!(population: 11_801_151)
Country.where(name: "Tunisia").first_or_create!.update!(population: 11_694_719)
Country.where(name: "Belgium").first_or_create!.update!(population: 11_539_328)
Country.where(name: "Bolivia").first_or_create!.update!(population: 11_513_100)
Country.where(name: "Cuba").first_or_create!.update!(population: 11_333_483)
Country.where(name: "Haiti").first_or_create!.update!(population: 11_263_770)
Country.where(name: "South Sudan").first_or_create!.update!(population: 11_062_113)
Country.where(name: "Burundi").first_or_create!.update!(population: 10_864_245)
Country.where(name: "Dominican Republic").first_or_create!.update!(population: 10_738_958)
Country.where(name: "Czech Republic").first_or_create!.update!(population: 10_689_209)
Country.where(name: "Greece").first_or_create!.update!(population: 10_473_455)
Country.where(name: "Portugal").first_or_create!.update!(population: 10_226_187)
Country.where(name: "Jordan").first_or_create!.update!(population: 10_101_694)
Country.where(name: "Azerbaijan").first_or_create!.update!(population: 10_047_718)
Country.where(name: "Sweden").first_or_create!.update!(population: 10_036_379)
Country.where(name: "United Arab Emirates").first_or_create!.update!(population: 9_770_529)
Country.where(name: "Honduras").first_or_create!.update!(population: 9_746_117)
Country.where(name: "Hungary").first_or_create!.update!(population: 9_684_679)
Country.where(name: "Belarus").first_or_create!.update!(population: 9_452_411)
Country.where(name: "Tajikistan").first_or_create!.update!(population: 9_321_018)
Country.where(name: "Austria").first_or_create!.update!(population: 8_955_102)
Country.where(name: "Papua New Guinea").first_or_create!.update!(population: 8_776_109)
Country.where(name: "Serbia").first_or_create!.update!(population: 8_772_235)
Country.where(name: "Switzerland").first_or_create!.update!(population: 8_591_365)
Country.where(name: "Israel").first_or_create!.update!(population: 8_519_377)
Country.where(name: "Togo").first_or_create!.update!(population: 8_082_366)
Country.where(name: "Sierra Leone").first_or_create!.update!(population: 7_813_215)
Country.where(name: "Hong Kong").first_or_create!.update!(population: 7_436_154)
Country.where(name: "Laos").first_or_create!.update!(population: 7_169_455)
Country.where(name: "Paraguay").first_or_create!.update!(population: 7_044_636)
Country.where(name: "Bulgaria").first_or_create!.update!(population: 7_000_119)
Country.where(name: "Lebanon").first_or_create!.update!(population: 6_855_713)
Country.where(name: "Libya").first_or_create!.update!(population: 6_777_452)
Country.where(name: "Nicaragua").first_or_create!.update!(population: 6_545_502)
Country.where(name: "El Salvador").first_or_create!.update!(population: 6_453_553)
Country.where(name: "Kyrgyzstan").first_or_create!.update!(population: 6_415_850)
Country.where(name: "Turkmenistan").first_or_create!.update!(population: 5_942_089)
Country.where(name: "Singapore").first_or_create!.update!(population: 5_804_337)
Country.where(name: "Denmark").first_or_create!.update!(population: 5_771_876)
Country.where(name: "Finland").first_or_create!.update!(population: 5_532_156)
Country.where(name: "Slovakia").first_or_create!.update!(population: 5_457_013)
Country.where(name: "Congo").first_or_create!.update!(population: 5_380_508)
Country.where(name: "Norway").first_or_create!.update!(population: 5_378_857)
Country.where(name: "Costa Rica").first_or_create!.update!(population: 5_047_561)
Country.where(name: "Palestine").first_or_create!.update!(population: 4_981_420)
Country.where(name: "Oman").first_or_create!.update!(population: 4_974_986)
Country.where(name: "Liberia").first_or_create!.update!(population: 4_937_374)
Country.where(name: "Ireland").first_or_create!.update!(population: 4_882_495)
Country.where(name: "New Zealand").first_or_create!.update!(population: 4_783_063)
Country.where(name: "Central African Republic").first_or_create!.update!(population: 4_745_185)
Country.where(name: "Mauritania").first_or_create!.update!(population: 4_525_696)
Country.where(name: "Panama").first_or_create!.update!(population: 4_246_439)
Country.where(name: "Kuwait").first_or_create!.update!(population: 4_207_083)
Country.where(name: "Croatia").first_or_create!.update!(population: 4_130_304)
Country.where(name: "Moldova").first_or_create!.update!(population: 4_043_263)
Country.where(name: "Georgia").first_or_create!.update!(population: 3_996_765)
Country.where(name: "Eritrea").first_or_create!.update!(population: 3_497_117)
Country.where(name: "Uruguay").first_or_create!.update!(population: 3_461_734)
Country.where(name: "Bosnia and Herzegovina").first_or_create!.update!(population: 3_301_000)
Country.where(name: "Mongolia").first_or_create!.update!(population: 3_225_167)
Country.where(name: "Armenia").first_or_create!.update!(population: 2_957_731)
Country.where(name: "Jamaica").first_or_create!.update!(population: 2_948_279)
Country.where(name: "Puerto Rico").first_or_create!.update!(population: 2_933_408)
Country.where(name: "Albania").first_or_create!.update!(population: 2_880_917)
Country.where(name: "Qatar").first_or_create!.update!(population: 2_832_067)
Country.where(name: "Lithuania").first_or_create!.update!(population: 2_759_627)
Country.where(name: "Namibia").first_or_create!.update!(population: 2_494_530)
Country.where(name: "Gambia").first_or_create!.update!(population: 2_347_706)
Country.where(name: "Botswana").first_or_create!.update!(population: 2_303_697)
Country.where(name: "Gabon").first_or_create!.update!(population: 2_172_579)
Country.where(name: "Lesotho").first_or_create!.update!(population: 2_125_268)
Country.where(name: "North Macedonia").first_or_create!.update!(population: 2_083_459)
Country.where(name: "Slovenia").first_or_create!.update!(population: 2_078_654)
Country.where(name: "Guinea-Bissau").first_or_create!.update!(population: 1_920_922)
Country.where(name: "Latvia").first_or_create!.update!(population: 1_906_743)
Country.where(name: "Bahrain").first_or_create!.update!(population: 1_641_172)
Country.where(name: "Trinidad and Tobago").first_or_create!.update!(population: 1_394_973)
Country.where(name: "Equatorial Guinea").first_or_create!.update!(population: 1_355_986)
Country.where(name: "Estonia").first_or_create!.update!(population: 1_325_648)
Country.where(name: "East Timor").first_or_create!.update!(population: 1_293_119)
Country.where(name: "Mauritius").first_or_create!.update!(population: 1_198_575)
Country.where(name: "Cyprus").first_or_create!.update!(population: 1_179_551)
Country.where(name: "Eswatini").first_or_create!.update!(population: 1_148_130)
Country.where(name: "Djibouti").first_or_create!.update!(population: 973_560)
Country.where(name: "Fiji").first_or_create!.update!(population: 889_953)
Country.where(name: "Réunion").first_or_create!.update!(population: 888_927)
Country.where(name: "Comoros").first_or_create!.update!(population: 850_886)
Country.where(name: "Guyana").first_or_create!.update!(population: 782_766)
Country.where(name: "Bhutan").first_or_create!.update!(population: 763_092)
Country.where(name: "Solomon Islands").first_or_create!.update!(population: 669_823)
Country.where(name: "Macau").first_or_create!.update!(population: 640_445)
Country.where(name: "Montenegro").first_or_create!.update!(population: 627_987)
Country.where(name: "Luxembourg").first_or_create!.update!(population: 615_729)
Country.where(name: "Western Sahara").first_or_create!.update!(population: 582_463)
Country.where(name: "Suriname").first_or_create!.update!(population: 581_372)
Country.where(name: "Cape Verde").first_or_create!.update!(population: 549_935)
Country.where(name: "Maldives").first_or_create!.update!(population: 530_953)
Country.where(name: "Guadeloupe").first_or_create!.update!(population: 447_905)
Country.where(name: "Malta").first_or_create!.update!(population: 440_372)
Country.where(name: "Brunei").first_or_create!.update!(population: 433_285)
Country.where(name: "Belize").first_or_create!.update!(population: 390_353)
Country.where(name: "Bahamas").first_or_create!.update!(population: 389_482)
Country.where(name: "Martinique").first_or_create!.update!(population: 375_554)
Country.where(name: "Iceland").first_or_create!.update!(population: 339_031)
Country.where(name: "Vanuatu").first_or_create!.update!(population: 299_882)
Country.where(name: "Barbados").first_or_create!.update!(population: 287_025)
Country.where(name: "New Caledonia").first_or_create!.update!(population: 282_750)
Country.where(name: "French Guiana").first_or_create!.update!(population: 282_731)
Country.where(name: "French Polynesia").first_or_create!.update!(population: 279_287)
Country.where(name: "Mayotte").first_or_create!.update!(population: 266_150)
Country.where(name: "São Tomé and Príncipe").first_or_create!.update!(population: 215_056)
Country.where(name: "Samoa").first_or_create!.update!(population: 197_097)
Country.where(name: "Saint Lucia").first_or_create!.update!(population: 182_790)
Country.where(name: "Guernsey and Jersey").first_or_create!.update!(population: 172_259)
Country.where(name: "Guam").first_or_create!.update!(population: 167_294)
Country.where(name: "Curaçao").first_or_create!.update!(population: 163_424)
Country.where(name: "Kiribati").first_or_create!.update!(population: 117_606)
Country.where(name: "F.S. Micronesia").first_or_create!.update!(population: 113_815)
Country.where(name: "Grenada").first_or_create!.update!(population: 112_003)
Country.where(name: "Tonga").first_or_create!.update!(population: 110_940)
Country.where(name: "Saint Vincent and the Grenadines").first_or_create!.update!(population: 110_589)
Country.where(name: "Aruba").first_or_create!.update!(population: 106_314)
Country.where(name: "U.S. Virgin Islands").first_or_create!.update!(population: 104_578)
Country.where(name: "Seychelles").first_or_create!.update!(population: 97_739)
Country.where(name: "Antigua and Barbuda").first_or_create!.update!(population: 97_118)
Country.where(name: "Isle of Man").first_or_create!.update!(population: 84_584)
Country.where(name: "Andorra").first_or_create!.update!(population: 77_142)
Country.where(name: "Dominica").first_or_create!.update!(population: 71_808)
Country.where(name: "Cayman Islands").first_or_create!.update!(population: 64_948)
Country.where(name: "Bermuda").first_or_create!.update!(population: 62_506)
Country.where(name: "Marshall Islands").first_or_create!.update!(population: 58_791)
Country.where(name: "Greenland").first_or_create!.update!(population: 56_672)
Country.where(name: "Northern Mariana Islands").first_or_create!.update!(population: 56_188)
Country.where(name: "American Samoa").first_or_create!.update!(population: 55_312)
Country.where(name: "Saint Kitts and Nevis").first_or_create!.update!(population: 52_823)
Country.where(name: "Faroe Islands").first_or_create!.update!(population: 48_678)
Country.where(name: "Sint Maarten").first_or_create!.update!(population: 42_388)
Country.where(name: "Monaco").first_or_create!.update!(population: 38_964)
Country.where(name: "Turks and Caicos Islands").first_or_create!.update!(population: 38_191)
Country.where(name: "Liechtenstein").first_or_create!.update!(population: 38_019)
Country.where(name: "San Marino").first_or_create!.update!(population: 33_860)
Country.where(name: "Gibraltar").first_or_create!.update!(population: 33_701)
Country.where(name: "British Virgin Islands").first_or_create!.update!(population: 30_030)
Country.where(name: "Caribbean Netherlands").first_or_create!.update!(population: 25_979)
Country.where(name: "Palau").first_or_create!.update!(population: 18_008)
Country.where(name: "Cook Islands").first_or_create!.update!(population: 17_548)
Country.where(name: "Anguilla").first_or_create!.update!(population: 14_869)
Country.where(name: "Tuvalu").first_or_create!.update!(population: 11_646)
Country.where(name: "Wallis and Futuna").first_or_create!.update!(population: 11_432)
Country.where(name: "Nauru").first_or_create!.update!(population: 10_756)
Country.where(name: "Saint Helena, Ascension and Tristan da Cunha").first_or_create!.update!(population: 6_059)
Country.where(name: "Saint Pierre and Miquelon").first_or_create!.update!(population: 5_822)
Country.where(name: "Montserrat").first_or_create!.update!(population: 4_989)
Country.where(name: "Falkland Islands").first_or_create!.update!(population: 3_377)
Country.where(name: "Niue").first_or_create!.update!(population: 1_615)
Country.where(name: "Tokelau").first_or_create!.update!(population: 1_340)
Country.where(name: "Vatican City").first_or_create!.update!(population: 799)
Country.where(name: "Others").first_or_create!
Country.where(name: 'Northern Ireland').first_or_create!.update!(population: 1_885_400)
Country.where(name: 'Saint Barthelemy').first_or_create!.update!(population: 9_793)
Country.where(name: 'South Africa').first_or_create!.update!(population: 58_775_022)
Country.where(name: 'St. Martin').first_or_create!.update!(population: 77_741)
Country.where(name: "Channel Islands").first_or_create!.update!(population: 170_499)
Country.where(name: 'Cruise Ship').first_or_create!
Country.where(name: 'Holy See').first_or_create!
Country.where(name: 'Kosovo').first_or_create!.update!(population: 1_810_463)
Country.where(name: 'MS Zaandam (Cruise Ship)').first_or_create!
